<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $Prducts=[
            [
                'name' => 'Молоко пастериз.',
                'price' => 109,
                'category'=>'MilkProduct',
                'description' => '930 мл',
                'image' => 'https://artalix.ru/thumb/2/JzNays-RN3qb8uMcA7l89A/150r150/d/moloko.jpg',
                'calories'=> 40,
            ],
            [
                'name' => 'Йогурт Чудо Клубника',
                'price' => 97,
                'category'=>'MilkProduct',
                'description' => '290 г',
                'image' => 'https://223-223.ru/media/products/10/419/987/10419987/resized/150x150_10419987.jpg',
                'calories'=> 20,
            ],
            [
                'name' => 'Творожок Чудо персик',
                'price' => 50,
                'category'=>'MilkProduct',
                'description' => '100 г',
                'image' => 'https://223-223.ru/media/products/10/419/997/10419997/resized/150x150_10419997.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Молоко Домик в дер.',
                'price' => 85,
                'category'=>'MilkProduct',
                'description' => '925 мл',
                'image' => 'https://sankt-peterburg.diamondelectric.ru/images/3332/3331289/small_moloko_domik_v_derevne_specialno_otobrannoe_yltrapasterizovannoe_1.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Десерт творожный Чудо',
                'price' => 50,
                'category'=>'MilkProduct',
                'description' => '100 г',
                'image' => 'https://cdn-irec.r-99.com/sites/default/files/imagecache/150o/product-images/2264822/z9EB3SIWaXYbz98dNJkKA.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Масло сливочное 82,5%',
                'price' => 188,
                'category'=>'MilkProduct',
                'description' => '180 г',
                'image' => 'https://i65.shop/upload/resize_cache/iblock/161/170_150_0/dj2ef1mn8x68oqolcv21r7lpe74eknrh.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Сметана Домик в деревне 15%',
                'price' => 66,
                'category'=>'MilkProduct',
                'description' => '300 г',
                'image' => 'https://метродом.рф/_sh/366/36627m_1.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Томаты ',
                'price' => 124,
                'category'=>'VegetablesProduct',
                'description' => '500 г',
                'image' => 'https://img2.tradewheel.com/uploads/images/products/2/4/fresh-indian-tomatoes0-0715564001553739312-150-.jpg.webp',
                'calories'=> 10,
            ],
            [
                'name' => 'Лук ',
                'price' => 50,
                'category'=>'VegetablesProduct',
                'description' => '500 г',
                'image' => 'https://www.freshmarkets.com.au/wp-content/uploads/2021/05/onion.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Огурцы',
                'price' => 204,
                'category'=>'VegetablesProduct',
                'description' => '500 г',
                'image' => 'https://agroshop.uz/upload/resize_cache/iblock/971/150_150_2/9712f843dce29c0893c5c0182634930b.jpeg',
                'calories'=> 10,
            ],
            [
                'name' => 'Картофель ',
                'price' => 16,
                'category'=>'VegetablesProduct',
                'description' => '1 кг',
                'image' => 'https://sun9-17.userapi.com/impf/Y8T87UShxfDgYeTC7zmiQEV9ezLVMH6BL7eJEg/xmOkuUVBNpc.jpg?size=150x150&quality=96&sign=5b078899e70538ac329bab41cd12d0d2&c_uniq_tag=RrG7sRsMKeZZftB4yVLkH74mq6PRVUluSIP6N5YWKYY&type=album',
                'calories'=> 10,
            ],
            [
                'name' => 'Перец красный',
                'price' => 135,
                'category'=>'VegetablesProduct',
                'description' => '500 г',
                'image' => 'https://i.pinimg.com/736x/a5/da/15/a5da154b4a607fa3077e2cce2127686a.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Свекла ',
                'price' => 10,
                'category'=>'VegetablesProduct',
                'description' => '500 г',
                'image' => 'https://i65.shop/upload/resize_cache/iblock/ee9/170_150_0/h4d6mvwibdezs0bp0ovc7500gd7j7eod.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Капуста',
                'price' => 105,
                'category'=>'VegetablesProduct',
                'description' => '3 кг',
                'image' => 'https://semenasibiri.tk/wp-content/uploads/2020/09/kapysta-150x150.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Чеснок ',
                'price' => 35,
                'category'=>'VegetablesProduct',
                'description' => '100 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=18c9da163f2ffeb6dd9274d854ec656fda990315-9029997-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Авокадо',
                'price' => 100,
                'category'=>'VegetablesProduct',
                'description' => '250 г',
                'image' => 'https://i.7fon.org/150/z165190.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Мандарины',
                'price' => 65,
                'category'=>'FruitsAndBerriesProduct',
                'description' => '500 г',
                'image' => 'https://images.deliveryhero.io/image/pim-glovo/65129edff393d00b6e9b0d5c.jpg?t=W3siYXV0byI6eyJxIjoibG93In19LHsicmVzaXplIjp7IndpZHRoIjoxNTAsImhlaWdodCI6MTUwfX1d',
                'calories'=> 40,
            ],
            [
                'name' => 'Лимоны',
                'price' => 25,
                'category'=>'FruitsAndBerriesProduct',
                'description' => '250 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=ccf05f3bfc9341b5c2eaecfa498a756e_sr-8439163-images-thumbs&n=13',
                'calories'=> 20,
            ],
            [
                'name' => 'Яблоко сезонное',
                'price' => 63,
                'category'=>'FruitsAndBerriesProduct',
                'description' => '500 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=bbaebc1f54f120af359c4e818a5c8fb2_sr-8981832-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Клубника красная',
                'price' => 80,
                'category'=>'FruitsAndBerriesProduct',
                'description' => '300 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=4ad382b2911f5697c5a34e0bec02fc0d_sr-10551030-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Груши Китайские',
                'price' => 101,
                'category'=>'FruitsAndBerriesProduct',
                'description' => '500 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=3a7152b1e64b775a19cbf9b07a2dc4f1-5486408-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Гранат',
                'price' => 175,
                'category'=>'FruitsAndBerriesProduct',
                'description' => '700 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=d2be4f3344b64af55751993e4a8403f6_sr-4229758-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Помело',
                'price' => 252,
                'category'=>'FruitsAndBerriesProduct',
                'description' => '1.4 кг',
                'image' => 'https://avatars.mds.yandex.net/i?id=718a7e7e30ab2a4fb53841361d5e4c79_sr-9098836-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Bounty Trio',
                'price' => 63,
                'category'=>'CandyProduct',
                'description' => '83 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=36d7c1de5104b3f89bbba1c74ca6821d_sr-4593014-images-thumbs&n=13',
                'calories'=> 40,
            ],
            [
                'name' => 'Шоколадные конфеты Twix',
                'price' => 150,
                'category'=>'CandyProduct',
                'description' => '200 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=2754eda1f2a6c1de287b414e8e9d7d06_sr-4902913-images-thumbs&n=13',
                'calories'=> 20,
            ],
            [
                'name' => 'Snickers',
                'price' => 60,
                'category'=>'CandyProduct',
                'description' => '81 г',
                'image' => 'https://dobavkam.net/files/styles/small/public/images/food/1203/4011100977716.jpg?itok=Mp5YAYiO',
                'calories'=> 10,
            ],
            [
                'name' => 'Пирожное Orion Choco Pie',
                'price' => 150,
                'category'=>'CandyProduct',
                'description' => '360 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=351535fdd4529c168e01551973c05ee3_sr-8159518-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => ' Picnic Big',
                'price' => 81,
                'category'=>'CandyProduct',
                'description' => '76 г',
                'image' => 'https://cdn-irec.r-99.com/sites/default/files/imagecache/150o/product-images/183986/GZvrs63ITAwgi70oKcRjjQ.jpeg',
                'calories'=> 10,
            ],
            [
                'name' => 'Медвеженок Барни',
                'price' => 89,
                'category'=>'CandyProduct',
                'description' => '150 г',
                'image' => 'https://avatars.mds.yandex.net/get-mpic/1715213/img_id679949275151513072.jpeg/150x150',
                'calories'=> 10,
            ],
            [
                'name' => 'Печенье Юбилейное',
                'price' => 97,
                'category'=>'CandyProduct',
                'description' => '268 кг',
                'image' => 'https://avatars.mds.yandex.net/i?id=c73e7f3695cf85de62a2a250f0be67d5_sr-10804261-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Бедро куриное охл.',
                'price' => 189,
                'category'=>'MeatAndBirdProduct',
                'description' => '1 кг',
                'image' => 'https://avatars.mds.yandex.net/i?id=d3bdd48f7b313e8bc28dbd7599504be6-4575634-images-thumbs&n=13',
                'calories'=> 40,
            ],
            [
                'name' => 'Фарш Мираторог',
                'price' => 220,
                'category'=>'MeatAndBirdProduct',
                'description' => '400 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=cd46116a4aaefd583d34fd944f1c6db8_sr-10700817-images-thumbs&n=13',
                'calories'=> 20,
            ],
            [
                'name' => 'Шницель свиной',
                'price' => 180,
                'category'=>'MeatAndBirdProduct',
                'description' => '400 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=51c717f63317eab7c3cbffd29c796675_sr-5220813-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Азу из индейки',
                'price' => 230,
                'category'=>'MeatAndBirdProduct',
                'description' => '500 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=030271dba3d04a16657e486490166ea4_sr-5273789-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Филе цыпленка-бройлера',
                'price' => 360,
                'category'=>'MeatAndBirdProduct',
                'description' => '800 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=c59cf84f8e1fd039886496eceb25e1e8_sr-4809837-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Фарш куриный',
                'price' => 171,
                'category'=>'MeatAndBirdProduct',
                'description' => '450 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=b5a1f35238f88c3d7ba2262d94f46ca9_sr-8263615-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Филе бедра охл.',
                'price' => 280,
                'category'=>'MeatAndBirdProduct',
                'description' => '410 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=eca066adfa01f6a7a1e5114edfa70e74_sr-5235819-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Икра деликатесная',
                'price' => 130,
                'category'=>'FishProduct',
                'description' => '180 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=0714e90b52b89414da75aeef9e4e96a6_sr-10350562-images-thumbs&n=13',
                'calories'=> 40,
            ],
            [
                'name' => 'Крабовое мясо',
                'price' => 120,
                'category'=>'FishProduct',
                'description' => '200 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=d947436d8d1e1e715e7578aca0280e40_sr-9098231-images-thumbs&n=13',
                'calories'=> 20,
            ],
            [
                'name' => 'Горбуша Fish House',
                'price' => 120,
                'category'=>'FishProduct',
                'description' => '245 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=4d74659ea883a056d056831bcb5650f5_sr-8176762-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Тунец Fish House',
                'price' => 130,
                'category'=>'FishProduct',
                'description' => '185 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=37b73f4573edd5f351fb07bc6ea4ff9e_sr-4408821-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Шпроты Вкусные консервы',
                'price' => 140,
                'category'=>'FishProduct',
                'description' => '240 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=ea477e8fcbc469a4b1fd9e2348c67b95_sr-4560943-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Крабовые палочки VICI',
                'price' => 170,
                'category'=>'FishProduct',
                'description' => '220 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=55776c1e182cc195fc4e8b6d5dafeed5_sr-5579164-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Форель Fish House',
                'price' => 180,
                'category'=>'FishProduct',
                'description' => '100 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=2fd8ef726ec2eacf22b2c764ed163f37_sr-6918470-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Наггетсы куриные Мираторг',
                'price' => 120,
                'category'=>'Freezing',
                'description' => '300 г',
                'image' => 'https://www.carefood.kz/upload/resize_cache/webp/250_250_1/kusochki_kur_zolotye_miratorg_1_105kg.webp',
                'calories'=> 40,
            ],
            [
                'name' => 'Чебупицца Гор.штучка Пепперони',
                'price' => 180,
                'category'=>'Freezing',
                'description' => '250 г',
                'image' => 'https://ir-3.ozone.ru/s3/multimedia-7/c250/6685537927.jpg',
                'calories'=> 20,
            ],
            [
                'name' => 'Мороженое Лакомка',
                'price' => 60,
                'category'=>'Freezing',
                'description' => '90 г',
                'image' => 'https://avatars.mds.yandex.net/get-mpic/1574389/img_id5259624210126551164.jpeg/6hq',
                'calories'=> 10,
            ],
            [
                'name' => 'Мороженое Коровка 15%',
                'price' => 70,
                'category'=>'Freezing',
                'description' => '100 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=dd2bb9952af36ba8a3c5e144ed7113af_sr-8273295-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Смесь овощная Global',
                'price' => 140,
                'category'=>'Freezing',
                'description' => '400 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=12491572753d3e9a832ef27b021ef8a7_sr-10303576-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Мороженое Колибри ',
                'price' => 50,
                'category'=>'Freezing',
                'description' => '100 г',
                'image' => 'https://avatars.mds.yandex.net/get-mpic/5235128/img_id2578157514834448890.jpeg/6',
                'calories'=> 10,
            ],
            [
                'name' => 'Наггетсы куриные Мираторг Классические',
                'price' => 200,
                'category'=>'Freezing',
                'description' => '300 г',
                'image' => 'https://avatars.mds.yandex.net/get-mpic/1417902/img_id8146710855828155226.jpeg/6hq',
                'calories'=> 10,
            ],
            [
                'name' => 'Энергет. напиток Adrenaline',
                'price' => 120,
                'category'=>'WaterAndDrinks',
                'description' => '449 мл',
                'image' => 'https://lyubimiigorod.ru/images/catalog/63ad3547cb71b.jpg',
                'calories'=> 40,
            ],
            [
                'name' => 'Напиток Манго Любимый',
                'price' => 190,
                'category'=>'WaterAndDrinks',
                'description' => '1.93 л',
                'image' => 'https://atoll-orel.ru/images/products/small/182738.jpg',
                'calories'=> 20,
            ],
            [
                'name' => 'Вода Красная цена',
                'price' => 49,
                'category'=>'WaterAndDrinks',
                'description' => '5 л',
                'image' => 'https://atoll-orel.ru/images/products/small/46473.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Напиток Добрый Cola',
                'price' => 130,
                'category'=>'WaterAndDrinks',
                'description' => '1.5 л',
                'image' => 'https://atoll-orel.ru/images/products/small/268111.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Напиток сильногаз. Cool Cola',
                'price' => 100,
                'category'=>'WaterAndDrinks',
                'description' => '1.5 л',
                'image' => 'https://gastrodom24.ru/upload/resize_cache/iblock/a6b/250_250_1/a6b2a7b2d39edfd0fa6acb0c1fe1febc.jpeg',
                'calories'=> 10,
            ],
            [
                'name' => 'Напиток Volt энерг.',
                'price' => 86,
                'category'=>'WaterAndDrinks',
                'description' => '450 мл',
                'image' => 'https://tilsit-market.ru/upload/resize_cache/iblock/4c4/250_250_1/3vzoa90z2npntqe67bs0v01k5hx35cll.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Чай Lipton Зеленый',
                'price' => 125,
                'category'=>'WaterAndDrinks',
                'description' => '1 л',
                'image' => 'https://static.insales-cdn.com/r/YYxFCQbiW9c/rs:fit:250:250:1/plain/images/products/1/2818/766438146/medium_import_files_4c_4cdd9e6e-05dc-11e6-9614-002590e5a7c6_a5a2adb9-4f85-11ed-9de7-0cc47aeb3cd9.jpeg',
                'calories'=> 10,
            ],
            [
                'name' => 'Сосиски Папа может',
                'price' => 310,
                'category'=>'Sausages',
                'description' => '600 г',
                'image' => 'https://i.otzovik.com/objects/b/1000000/993976.png',
                'calories'=> 40,
            ],
            [
                'name' => 'Колбаса Вязанка вареная',
                'price' => 300,
                'category'=>'Sausages',
                'description' => '450 г',
                'image' => 'https://shop.mercury-market.ru/upload/resize_cache/iblock/03a/250_250_1/b3ym1d17d83w0j43e6xyh01jve3n30ny.jpeg',
                'calories'=> 20,
            ],
            [
                'name' => 'Колбаса Папа Может',
                'price' => 100,
                'category'=>'Sausages',
                'description' => '300 г',
                'image' => 'https://treshkamarket.ru/upload/resize_cache/iblock/bd3/250_250_1/bd3406907734742bcaee62d0105e8855.jpeg',
                'calories'=> 10,
            ],
            [
                'name' => 'Сосиски Ядрена копоть ',
                'price' => 120,
                'category'=>'Sausages',
                'description' => '420 г',
                'image' => 'https://avatars.mds.yandex.net/get-mpic/5163819/img_id5666658909758433031.png/6',
                'calories'=> 10,
            ],
            [
                'name' => 'Сервелат Папа Может ',
                'price' => 320,
                'category'=>'Sausages',
                'description' => '350 г',
                'image' => 'https://4да.рф/upload/resize_cache/iblock/23b/250_250_1/zsebeq9vhq5vf435hje9k8unojbnjss1.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Бекон Мясная Ферма ',
                'price' => 120,
                'category'=>'Sausages',
                'description' => '150 г',
                'image' => 'https://i.03market.ru/cicon/1927699/img_id3811301653825382699.jpeg/6hq',
                'calories'=> 10,
            ],
            [
                'name' => 'Сосиски Вязанка Сливушки',
                'price' => 250,
                'category'=>'Sausages',
                'description' => '330 г',
                'image' => 'https://i.otzovik.com/objects/b/1740000/1736540.png',
                'calories'=> 10,
            ],
            [
                'name' => 'Хлеб Harrys American ',
                'price' => 110,
                'category'=>'Bread',
                'description' => '470 г',
                'image' => 'https://avatars.mds.yandex.net/get-mpic/1767151/img_id663230384997106681.jpeg/6hq',
                'calories'=> 40,
            ],
            [
                'name' => 'Батон Хлебный дом',
                'price' => 57,
                'category'=>'Bread',
                'description' => '350 г',
                'image' => 'https://to-eat.ru/upload/resize_cache/iblock/825/85m6z2nbgrbve00x5xc99b6xu7yrzquf/250_250_1/baton_khlebnyy_dom_zvezdnyy_pshenichnyy_narezannyy_350_g.jpg',
                'calories'=> 20,
            ],
            [
                'name' => 'Лепёшки пшеничные',
                'price' => 120,
                'category'=>'Bread',
                'description' => '250 г',
                'image' => 'https://avatars.mds.yandex.net/i?id=01c0fee848d581cd5ba3e8da6c728c31_sr-12650537-images-thumbs&n=13',
                'calories'=> 10,
            ],
            [
                'name' => 'Булочка Bagerstat',
                'price' => 160,
                'category'=>'Bread',
                'description' => '240 г',
                'image' => 'https://atoll-orel.ru/images/products/small/262684.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Крендельки Зерница с солью',
                'price' => 33,
                'category'=>'Bread',
                'description' => '100 г',
                'image' => 'https://i.otzovik.com/objects/b/1020000/1019363.png',
                'calories'=> 10,
            ],
            [
                'name' => 'Хлебцы цельнозерновые',
                'price' => 54,
                'category'=>'Bread',
                'description' => '100 г',
                'image' => 'https://shop22.mgnl.ru/upload/iblock/472/m3yosq4l2kxg2xxaeoy6jfkfhhnk66e5.jpeg',
                'calories'=> 10,
            ],
            [
                'name' => 'Пирог Шарлиз с вишневым джемом',
                'price' => 170,
                'category'=>'Bread',
                'description' => '430 г',
                'image' => 'https://i.otzovik.com/objects/b/1970000/1965851.png',
                'calories'=> 10,
            ],
            [
                'name' => 'Сыр Ламбер 50%',
                'price' => 280,
                'category'=>'cheese',
                'description' => '230 г',
                'image' => 'https://ir.ozone.ru/s3/multimedia-p/c250/6532511053.jpg',
                'calories'=> 40,
            ],
            [
                'name' => 'Сыр Красная цена',
                'price' => 175,
                'category'=>'cheese',
                'description' => '350 г',
                'image' => 'https://avatars.mds.yandex.net/get-mpic/1767151/img_id6967346876783320666.jpeg/6hq',
                'calories'=> 20,
            ],
            [
                'name' => 'Сыр тостовый Hochland',
                'price' => 100,
                'category'=>'cheese',
                'description' => '150 г',
                'image' => 'https://static.insales-cdn.com/r/phaFsAeG-Ec/rs:fit:250:250:1/plain/images/products/1/708/766419652/medium_import_files_6c_6ccb914b-0834-44c7-92d9-f74bfe9ae2d1_254befd1-3e33-11ed-9de7-0cc47aeb3cd9.jpeg',
                'calories'=> 10,
            ],
            [
                'name' => 'Сыр твёрдый LiebenDorf',
                'price' => 190,
                'category'=>'cheese',
                'description' => '200 г',
                'image' => 'https://i.otzovik.com/objects/b/1860000/1857230.png',
                'calories'=> 10,
            ],
            [
                'name' => 'Сыр полутвердый 45%',
                'price' => 180,
                'category'=>'cheese',
                'description' => '200 г',
                'image' => 'https://shop.mercury-market.ru/upload/resize_cache/iblock/d3d/250_250_1/3tftku6au97r55osq2a3rs1l6yh0rikd.jpeg',
                'calories'=> 10,
            ],
            [
                'name' => 'Сыр плавленый Hochland 55%',
                'price' => 175,
                'category'=>'cheese',
                'description' => '200 г',
                'image' => 'https://1ya.ru/media/cache/list_thumb/https---avatars.mds.yandex.net/get-mpic/1767151/img_id3803613831542921019.jpeg/9',
                'calories'=> 10,
            ],
            [
                'name' => 'Сыр творожный Hochland ',
                'price' => 185,
                'category'=>'cheese',
                'description' => '220 г',
                'image' => 'https://zakaz-everest-shop.ru/upload/resize_cache/iblock/d0d/250_250_1/4djpqlfss1m2n8itcegi647nft2jd8dz.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Сахар белый песок',
                'price' => 62,
                'category'=>'PastaAndCereals',
                'description' => '1 кг',
                'image' => 'https://gastrodom24.ru/upload/resize_cache/iblock/711/250_250_1/711fa587dd51c2a764d0f2a00998a668.jpeg',
                'calories'=> 40,
            ],
            [
                'name' => 'Доширак с курицей',
                'price' => 65,
                'category'=>'PastaAndCereals',
                'description' => '90 г',
                'image' => 'https://cdn.100sp.ru/cache_pictures/101013680/thumb300',
                'calories'=> 20,
            ],
            [
                'name' => 'Макароны Makfa Витки',
                'price' => 55,
                'category'=>'PastaAndCereals',
                'description' => '450 г',
                'image' => 'https://shop.mercury-market.ru/upload/resize_cache/iblock/29c/250_250_1/my7wricn0pzs4yymydyf9pcqv9qnlmkc.jpeg',
                'calories'=> 10,
            ],
            [
                'name' => 'Макароны Makfa Улитки',
                'price' => 55,
                'category'=>'PastaAndCereals',
                'description' => '450 г',
                'image' => 'https://rahatmarket.ru/pictures/product/middle/14635_middle.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Макаронные изделия Barilla',
                'price' => 99,
                'category'=>'PastaAndCereals',
                'description' => '450 г',
                'image' => 'https://posyltorg33.ru/upload/iblock/e9c/e9c51429d1080882848ecdeefac4b544.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Спагетти ТМ Makfa',
                'price' => 66,
                'category'=>'PastaAndCereals',
                'description' => '450 г',
                'image' => 'https://atoll-orel.ru/images/products/small/150665.jpg',
                'calories'=> 10,
            ],
            [
                'name' => 'Гречка ядрица Селяночка',
                'price' => 85,
                'category'=>'PastaAndCereals',
                'description' => '900 г',
                'image' => 'https://avatars.mds.yandex.net/get-mpic/1571231/img_id2546363084336350950.jpeg/6hq',
                'calories'=> 10,
            ],
        ];
        Product::insert($Prducts);
    }
}
